# Generated by Django 4.2.4 on 2023-09-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todolist', '0002_todolist_test2'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='test3',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
