# Generated by Django 4.2.4 on 2023-09-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todolist', '0003_todolist_test3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='test',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='test2',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='test3',
        ),
    ]
