# Generated by Django 4.2.4 on 2023-09-05 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Todolist', '0004_remove_todolist_test_remove_todolist_test2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
